### PR TITLE
Updating dependencies

### LINKED ISSUE #121: Update dependencies and add badge
We have quite a few outdated dependencies at the moment:

```
C:\repos\harmonic>npm outdated --depth 0
Package     Current  Wanted  Latest  Location
less          1.7.5   1.7.5   2.4.0  less
ncp           0.5.1   0.5.1   2.0.0  ncp
stylus       0.45.1  0.45.1  0.50.0  stylus
commander     2.2.0   2.2.0   2.6.0  commander
chalk         0.5.1   0.5.1   1.0.0  chalk
permalinks    0.2.1   0.2.1   0.3.1  permalinks
should        4.6.5   4.6.5   5.0.1  should
co            3.0.6   3.0.6   4.4.0  co
```

After updating the dependencies, we can add these badges to help us keep track of the dependencies status:

[Dependency Status](https://david-dm.org/es6rocks/harmonic)
[devDependency Status](https://david-dm.org/es6rocks/harmonic#info=devDependencies)

### PR DESCRIPTION
**Pull request by jaydson**
I've identified 2 unnecessary dependencies: `marked` and `markdown-extra`.
Both dependencies were removed.

The below dependencies were updated to its latest version:
```json
"babel-runtime": "^4.7.13",
"cli-color": "^0.3.2",
"co-prompt": "^1.0.0",
"commander": "^2.7.1",
"less": "^2.4.0",
"marked-metadata": "0.0.6",
"mkdirp": "^0.5.0",
"ncp": "^2.0.0",
"node-static": "^0.7.6",
"nunjucks": "^1.2.0",
"open": "0.0.5",
"permalinks": "^0.3.1",
"rimraf": "^2.3.2",
"stylus": "^0.50.0",
"underscore": "^1.8.2"
```
I tried to update `co` to its latest version but it breaks the config command.
`co` version must to stay in ~3.0.5 until we remove it.

The below dev-dependencies were updated to its latest version:
```json
"chalk": "^1.0.0",
"glob-manipulate": "^1.1.1",
"gulp": "^3.8.11",
"gulp-babel": "^4.0.0",
"gulp-batch": "^1.0.5",
"gulp-filter": "^2.0.2",
"gulp-jscs": "^1.4.0",
"gulp-jshint": "^1.9.2",
"gulp-load-plugins": "^0.8.1",
"gulp-mocha": "^2.0.0",
"gulp-rename": "^1.2.0",
"gulp-src-ordered-globs": "^1.0.3",
"gulp-util": "^3.0.4",
"gulp-watch": "^4.2.0",
"jshint-stylish": "^1.0.1",
"lazypipe": "^0.2.2",
"merge-stream": "^0.1.7",
"reversepoint": "^0.2.1",
"should": "^5.2.0",
"through": "^2.3.6",
"unique-stream": "^2.0.2",
"vinyl-paths": "^1.0.0"
```
All Harmonic features were well tested and it seems to be working just fine with the update.
Perhaps some review will be necessary //cc @UltCombo 

This PR partially closes #121 as we still need to add the badges.

### CODE REVIEW

**Comment by UltCombo** [comment]
Nice work! But isn't the `marked` module that parses our markdown (posts, pages) files?

**Comment by UltCombo** [comment]
I have a full day tomorrow so I probably won't be able to test this throughout soon.

**Comment by jaydson** [comment]
The package [marked-metadata](https://www.npmjs.com/package/marked-metadata) does the job.

**Comment by UltCombo** [comment]
Oh I see, nice!

**Comment by UltCombo** [comment]
Now I have time to test. Looks like everything is working fine indeed, nice work @jaydson!
I'll add the badges and merge this. `=]`

**Comment by UltCombo** [comment]
:+1:

**Comment by jaydson** [comment]
wow awesome!

**Pull request merged**
