### PR TITLE
New logo

### PR DESCRIPTION
**Pull request by UltCombo**
See the new header here: https://github.com/es6rocks/harmonic/tree/new-logo

### CODE REVIEW

**Comment by UltCombo** [comment]
@jaydson does this look good for merging?
I'm fixing some small details regarding linking atm.

**Comment by UltCombo** [comment]
I was trying to make the `#harmonic` fragment link to the README's title, it works now: https://github.com/es6rocks/harmonic/tree/new-logo
It works now, but GitHub is adding an extra paragraph due to the anchor and that results in too much margin-top.

**Comment by UltCombo** [comment]
I've removed the link which GitHub automatically adds to images from the logo (which was uselessly linking to the image source) by explicitly wrapping the logo with an anchor. In the future, the logo image could link to the Harmonic site (which is work in progress).

@jaydson think we can merge this? Is the logo size okay?

**Comment by UltCombo** [comment]
@italowaxman @jaydson can you guys take a look at the readme's [new header](https://github.com/es6rocks/harmonic/tree/new-logo#harmonic)? Is it too small or too big? (feel free to experiment changing the size through the DevTools)
Any other suggestions/comments?

**Comment by italowaxman** [comment]
Its ok for me. Tell me something, can i make a header image to occupy 100% of the space?

**Comment by jaydson** [comment]
Seems perfect to me.

**Comment by UltCombo** [comment]
@italowaxman I think it is not really necessary -- the logo alone is good for branding. I don't know what you have in mind though, so feel free to experiment if you have too much spare time, but the Harmonic site should be a much higher priority at the moment.

**Comment by italowaxman** [comment]
No problem @UltCombo, then we will focus on the creation of harmonic website.

**Pull request merged**
